### ISSUE TITLE
ReadRequest Struct throwing error

### ISSUE THREAD

**Issue by prdsoftware** [SteveSandersonMS/BlazorInputFile#13]
Hi Steve,

Thanks for making this component.  The Nuget package works great, however when we try to use the source code in a project, we get the following error:

Could not load type 'ReadRequest' from assembly 'XXXX, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' because it contains an object field at offset 4 that is incorrectly aligned or overlapped by a non-object field.

Here's the struct:

[StructLayout(LayoutKind.Explicit)]
        public struct ReadRequest
        {
            [FieldOffset(0)] public string InputFileElementReferenceId;
            [FieldOffset(4)] public int FileId;
            [FieldOffset(8)] public long SourceOffset;
            [FieldOffset(16)] public byte[] Destination;
            [FieldOffset(20)] public int DestinationOffset;
            [FieldOffset(24)] public int MaxBytes;
        }

Using:
- Visual Studio 16.4.2 Preview 2
- Dot Net Core 3.1
- Blazor Server Side

Any ideas?

Thanks in advance.
Rod

**Comment by periapsistech** [comment]
@prdsoftware It's an issue with compiling for x64 platforms - just remove the [StructLayout(LayoutKind.Explicit)] and [FieldOffset()] attributes.

**Comment by prdsoftware** [comment]
Great!  Thanks for the info.  We'll give that a go.

**Comment by prdsoftware** [comment]
@periapsistech  Thanks again for the tip.  Just confirming that removing the StructLayout and FieldOffset attributes worked as you mentioned.
